### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aomayan24** [Imagine-YT/Roblox-Account-Generator#26]
Traceback (most recent call last):
  File "C:\Users\aomay\Downloads\Roblox-Account-Generator\main.py", line 276, in <module>
    starter()
  File "C:\Users\aomay\Downloads\Roblox-Account-Generator\main.py", line 267, in starter
    main()
  File "C:\Users\aomay\Downloads\Roblox-Account-Generator\main.py", line 122, in main
    driver = webdriver.Chrome(service=service, options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

**Comment by Imagine-YT** [comment]
I have discontinued the project. Do expect errors.
