### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DolceJ0Lly** [Imagine-YT/Roblox-Account-Generator#37]
Hi,

                        ██████╗░░█████╗░██████╗░██╗░░░░░░█████╗░██╗░░██╗  ░██████╗░███████╗███╗░░██╗
                        ██╔══██╗██╔══██╗██╔══██╗██║░░░░░██╔══██╗╚██╗██╔╝  ██╔════╝░██╔════╝████╗░██║
                        ██████╔╝██║░░██║██████╦╝██║░░░░░██║░░██║░╚███╔╝░  ██║░░██╗░█████╗░░██╔██╗██║
                        ██╔══██╗██║░░██║██╔══██╗██║░░░░░██║░░██║░██╔██╗░  ██║░░╚██╗██╔══╝░░██║╚████║
                        ██║░░██║╚█████╔╝██████╦╝███████╗╚█████╔╝██╔╝╚██╗  ╚██████╔╝███████╗██║░╚███║
                        ╚═╝░░╚═╝░╚════╝░╚═════╝░╚══════╝░╚════╝░╚═╝░░╚═╝  ░╚═════╝░╚══════╝╚═╝░░╚══╝

                                                   >> Made By Imagine
                                                   >> Version 2.2
                                                   >> Last Update: Inappropriate Name Check + Patch
                                                   >> Current Update: NopeCHA Key Support
                                                   >> Next Update: IDK
                                                   >> Generating 30 Accounts

Traceback (most recent call last):
  File "C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main\main.py", line 276, in <module>
    starter()
  File "C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main\main.py", line 267, in starter
    main()
  File "C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main\main.py", line 110, in main
    starter()
  File "C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main\main.py", line 261, in starter
    starter()
  File "C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main\main.py", line 267, in starter
    main()
  File "C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main\main.py", line 122, in main
    driver = webdriver.Chrome(service=service, options=options)
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\UTENTE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 106
Current browser version is 119.0.6045.124 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00651ED3+2236115]
        Ordinal0 [0x005E92F1+1807089]
        Ordinal0 [0x004F66FD+812797]
        Ordinal0 [0x00518C6D+953453]
        Ordinal0 [0x00514200+934400]
        Ordinal0 [0x005119C9+924105]
        Ordinal0 [0x0054806C+1146988]
        Ordinal0 [0x00547A6A+1145450]
        Ordinal0 [0x005418A6+1120422]
        Ordinal0 [0x0051A73D+960317]
        Ordinal0 [0x0051B71F+964383]
        GetHandleVerifier [0x008FE7E2+2743074]
        GetHandleVerifier [0x008F08D4+2685972]
        GetHandleVerifier [0x006E2BAA+532202]
        GetHandleVerifier [0x006E1990+527568]
        Ordinal0 [0x005F080C+1837068]
        Ordinal0 [0x005F4CD8+1854680]
        Ordinal0 [0x005F4DC5+1854917]
        Ordinal0 [0x005FED64+1895780]
        BaseThreadInitThunk [0x7669FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77607C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77607C3E+238]

C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main>
C:\Users\UTENTE\Desktop\fi\Roblox-Account-Generator-main>

**Comment by DolceJ0Lly** [comment]
tried with & without random users, tryed with 30 gen but 0 real gen.

**Comment by UniversalStorage** [comment]
do you have the chrome driver.exe in the directory as the source?

**Comment by DolceJ0Lly** [comment]
I got in the chrome driver folder, I install the repository how is it. So I
don't do anything only "python main.py"

Il dom 12 nov 2023, 03:33 UniversalStorage ***@***.***> ha
scritto:

**Comment by Imagine-YT** [comment]
![image](https://github.com/Imagine-YT/Roblox-Account-Generator/assets/74649094/9b594cc1-9120-4edd-808b-d2f3c0da732d)

**Comment by DolceJ0Lly** [comment]
bro just updated the readme so people thinks that i dont read the readme, bro needs to do something to say to people that others devs are crazy 🤦‍♂️🤦‍♂️🤦‍♂️💀💀💀💀
