### ISSUE TITLE
errors after following instructions

### ISSUE THREAD

**Issue by ZorkIsEmo** [Imagine-YT/Roblox-Account-Generator#8]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 97, in start
    path = SeleniumManager.driver_location(browser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 68, in driver_location
    result = SeleniumManager.run(args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 85, in run
    raise WebDriverException(f"Unsuccessful command executed: {args}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: ('C:\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe', '--browser', 'chrome')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zorkf\OneDrive\Desktop\Roblox Account Manager\Roblox Account Generator\main.py", line 255, in <module>
    starter()
  File "C:\Users\zorkf\OneDrive\Desktop\Roblox Account Manager\Roblox Account Generator\main.py", line 246, in starter
    main()
  File "C:\Users\zorkf\OneDrive\Desktop\Roblox Account Manager\Roblox Account Generator\main.py", line 117, in main
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "C:\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 103, in __init__
    self.service.start()
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 100, in start
    raise err
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 91, in start
    self._start_process(self.path)
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 203, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by Imagine-YT** [comment]
hmm, did you download the compatible version of chromedriver?
Read "READ ME FIRST.TXT" once. If you have any more issues then let me know / add me on discord: Imagine#5120

**Comment by ZorkIsEmo** [comment]
figured it out that i didn't have chrome installed since i use opera, me big dum dum

**Comment by Imagine-YT** [comment]
oh, glad to know that you can run the gen now!
