### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Xarond12** [Imagine-YT/Roblox-Account-Generator#9]
Traceback (most recent call last):
  File "C:\Users\Xarond\Desktop\Roblox-Account-Generator-main\main.py", line 260, in <module>
    starter()
  File "C:\Users\Xarond\Desktop\Roblox-Account-Generator-main\main.py", line 251, in starter
    main()
  File "C:\Users\Xarond\Desktop\Roblox-Account-Generator-main\main.py", line 134, in main
    month.click()
  File "C:\Users\Xarond\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Xarond\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xarond\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Xarond\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <select class="rbx-select" id="MonthDropdown" name="birthdayMonth">...</select> is not clickable at point (492, 441). Other element would receive the click: <div class="cookie-banner-bg" aria-hidden="true"></div>
  (Session info: chrome=107.0.5304.121)
Stacktrace:
Backtrace:
        Ordinal0 [0x0070ACD3+2075859]
        Ordinal0 [0x0069EE61+1633889]
        Ordinal0 [0x0059B7BD+571325]
        Ordinal0 [0x005D1499+791705]
        Ordinal0 [0x005CF4AC+783532]
        Ordinal0 [0x005CD0AB+774315]
        Ordinal0 [0x005CBD37+769335]
        Ordinal0 [0x005C1C76+728182]
        Ordinal0 [0x005E731C+881436]
        Ordinal0 [0x005C15BF+726463]
        Ordinal0 [0x005E7534+881972]
        Ordinal0 [0x005FB56A+963946]
        Ordinal0 [0x005E7136+880950]
        Ordinal0 [0x005BFEFD+720637]
        Ordinal0 [0x005C0F3F+724799]
        GetHandleVerifier [0x009BEED2+2769538]
        GetHandleVerifier [0x009B0D95+2711877]
        GetHandleVerifier [0x0079A03A+521194]
        GetHandleVerifier [0x00798DA0+516432]
        Ordinal0 [0x006A682C+1665068]
        Ordinal0 [0x006AB128+1683752]
        Ordinal0 [0x006AB215+1683989]
        Ordinal0 [0x006B6484+1729668]
        BaseThreadInitThunk [0x7627FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x77747BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77747B8E+238]

**Comment by RobloxArchiver** [comment]
Did you close the ChromeDriver window?

**Comment by Imagine-YT** [comment]
Hmm, seems like the cookie error. I'm sorry, this is a hard one to fix as I don't have the element IDs.
